Repository c-r-u-x/crux-iOS, pull requests merged in 2024-06, with the labels that each got.

#4 [feat] create base tab view
  README.md
  cliary/cliary.xcodeproj/project.pbxproj
  cliary/cliary/App/SceneDelegate.swift
  cliary/cliary/Presenter/Auth/LoginViewController.swift
  cliary/cliary/Presenter/Navigation/NavigationController.swift
  cliary/cliary/Presenter/TabBar/TabBarViewController.swift
Labels: enhancement

#9 [feat] create base tab view
  cliary/cliary.xcodeproj/project.pbxproj
  cliary/cliary/App/SceneDelegate.swift
  cliary/cliary/Presenter/Auth/LoginViewController.swift
  cliary/cliary/Presenter/Navigation/NavigationController.swift
  cliary/cliary/Presenter/TabBar/TabBarViewController.swift
Labels: enhancement

#10 [chore] created pr template
  .github/pull_request_template.md
  README.md
  cliary/cliary.xcodeproj/project.pbxproj
  cliary/cliary/App/SceneDelegate.swift
  cliary/cliary/App/ViewController.swift
  cliary/cliary/Presenter/Navigation/NavigationController.swift
  cliary/cliary/Presenter/TabBar/TabBarViewController.swift
Labels: chore

#12 chore: created pull request template
  .github/pull_request_template.md
Labels: chore

#15 fix: added missing folder and file to the pbxproj #13
  cliary/cliary.xcodeproj/project.pbxproj
Labels: bug

#17 Refactor: TabBarViewController 리팩토링
  cliary/cliary.xcodeproj/project.pbxproj
  cliary/cliary/Presenter/TabBar/TabBarViewController.swift
Labels: refactor
